receivers:
  awsecscontainermetrics:
    collection_interval: 60s

  prometheus:
    config:
      global:
        scrape_interval: 60s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "Node_Exporter"
        static_configs:
        - targets: [ node_exporter:9100 ]
          labels:
            server: 'test'

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheusremotewrite:
    endpoint: "<endpoint>"
    resource_to_telemetry_conversion:
      enabled: true

  awsxray:
    region: "ap-northeast-1"

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check, sigv4auth]
  pipelines:
    metrics:
      receivers: [awsecscontainermetrics,prometheus]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [awsxray]
